### ISSUE TITLE
Could use `upstream-version` to convey "release candidate"

### ISSUE THREAD

**Issue by boris-kolpackov** [lyrahgames/build2-tinyobjloader#2]
Just a minor idea/suggestion: I see you mapped rc10 to beta10, which is correct. However, if you can want to convey that this is a release candidate, you could add `upstream-version` to `manifest`:

```
upstream-version: 2.0.0-rc.10
```

For details, see: https://build2.org/stage/bpkg/doc/build2-package-manager-manual.xhtml#manifest-package-version

**Comment by lyrahgames** [comment]
Thanks for the suggestion. Yes, I would like to do that. But I am unsure about the specific spelling as the upstream repository got a little inconsistent after version `1.0.6` when it comes to its release candidates. Tags are called `v2.0.0rc10` or `v2.0.0-rc1`. Releases are also called `v2.0-rc1`. Based on that, I would try to stick to the spelling of the specific version inside the upstream version, like in the following. Does this make sense?

```
upstream-version: 2.0.0-rc1
upstream-version: 2.0.0rc10
```
Or would you rather use a more consistent upstream version string, like in your text?

> ```
> upstream-version: 2.0.0-rc.10
> ```

**Comment by boris-kolpackov** [comment]
While you can specify anything in `upstream-version` (it's just a string for information purposes), it's a good idea to stick to what upstream uses. I took the version from `CMakeLists.txt` in the root of the repository, which feels authoritative enough.

**Comment by lyrahgames** [comment]
Fixed it. [Here](https://ci.cppget.org/@4a3b1e4e-7ee4-400c-ae11-bf4dfb26c49e) is the up-to-date CI run. I have published a new package revision.
